"""add ready designs support

Revision ID: 1a360e5ca022
Revises: b5641cbdc117
Create Date: 2025-12-22 10:04:01.791928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a360e5ca022'
down_revision: Union[str, Sequence[str], None] = 'b5641cbdc117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('price_mdl', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.add_column('orders', sa.Column('order_kind', sa.String(length=20), server_default='custom', nullable=False))
    op.add_column('orders', sa.Column('design_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('personal_text', sa.String(length=30), nullable=True))
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_foreign_key(None, 'orders', 'designs', ['design_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('orders', 'personal_text')
    op.drop_column('orders', 'design_id')
    op.drop_column('orders', 'order_kind')
    op.drop_table('designs')
    # ### end Alembic commands ###
